### ISSUE TITLE
mod broken :(

### ISSUE THREAD

**Issue by TTVMinnieMagma** [jakzo/EndnightMods#1]
mod no longer works because of 1.0
it need to be updated I've tried installing it 4 times and no extra kelvins :(

**Comment by bomboclatje** [comment]
Yup, I guess we'll just have to wait

**Comment by iamfj** [comment]
```
[Info   :KelvinCloner] Cloning Kelvin
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Sons.Characters.CharacterManager Sons.Characters.CharacterManager.get_Instance()'.
   at Jakzo.EndnightMods.KelvinCloner.Cloner.SpawnRobby()
   at Trampoline_VoidThisJakzo.EndnightMods.KelvinCloner.ClonerUpdate(IntPtr , Il2CppMethodInfo* )
[Info   :KelvinCloner] Cloning Kelvin
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Sons.Characters.CharacterManager Sons.Characters.CharacterManager.get_Instance()'.
   at Jakzo.EndnightMods.KelvinCloner.Cloner.SpawnRobby()
   at Trampoline_VoidThisJakzo.EndnightMods.KelvinCloner.ClonerUpdate(IntPtr , Il2CppMethodInfo* )
[Info   :KelvinCloner] Cloning Kelvin
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Sons.Characters.CharacterManager Sons.Characters.CharacterManager.get_Instance()'.
   at Jakzo.EndnightMods.KelvinCloner.Cloner.SpawnRobby()
   at Trampoline_VoidThisJakzo.EndnightMods.KelvinCloner.ClonerUpdate(IntPtr , Il2CppMethodInfo* )

```

**Comment by jakzo** [comment]
Finally got around to looking at this, but the mod is working fine for me. 🤔 I'm on the current build on Steam. The stack trace above shows that `Sons.Characters.CharacterManager.Instance` doesn't exist but it does on my game so there's not much I can do to fix it. 🤷
